- name: data types
  hosts: remote
  vars:
    COURSE: "I am learning Devops"
    Tools:
    - Linux
    - ANSIBLE
    - SHELL
    EXPERIANCE:
      Devops: 3
      AAWS: 2
      CICD: 2
    Realtime: yes 
  tasks:
  - name: data types call
    ansible.builtin.debug:
       msg: "Hi am learning {{COURSE}}, require tools: {{Tools}}, total years experiance in {{EXPERIANCE}}, its a realtime {{Realtime}}"