- name: condition
  hosts: remote 
  become: yes
  tasks:
  - name: user verification
    ansible.builtin.command: id Naga
    register: USER
    ignore_errors: true


  - name: print user infomation
    ansible.builtin.debug:
      msg: "user info {{USER}}"

  - name: create user
    ansible.builtin.command: useradd Naga
    when: USER.rc != 0