- name: Conditions
  hosts: remote
  become: yes
  tasks:
  - name: user info
    ansible.builtin.command: id Naga
    registry: USER
    ignore_error: yes

  - name: pring user info
    ansible.builtin.debug:
      msg: "pring user info {{USER}}"
      
  - name: user create
    ansible.builtin.command: useradd Naga
    when: USER.tc != 0