- name: install nginx
  hosts: remote 
  become: yes 
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest 

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 

  - name: stop the nginx
    ansible.builtin.service:
       name: nginx
       state: stopped
  - name: remove the nginx
    ansible.builtin.dnf:
      name: nginx
      state: removed 




