- name: install nginx
  hosts: web
  become: yes
  tasks: 
  - name: install the nginx
    ansible.builtin.dnf:
    name: nginx
    state: latest
  
  - name: start the service 
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

