- name: Variables
  hosts: remote
  vars:
    COURSE: "DEVOPS"
    TRAINER: "SIVE"
    DURATION: "3 months"
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}}, Triner is: {{TRAINER}}, Duration take: {{DURATION}}"