- name: variable task
  hosts: remote 
  vars:
    COURSE: "DEVOPS"
    TRINER: "SIVA"
    DURATION: "3 Months"
  tasks:
  - name: Varible in task level
    vars:
      COURSE: "AWS"
    ansible.builtin.debug:
      msg: "i am learing {{COURSE}}, Triner is: {{TRINER}}, Course Duration is {{DURATION}}"

  - name: variable
    ansible.builtin.debug:
      msg: "i am learing {{COURSE}}, Triner is: {{TRINER}}, Course Duration is {{DURATION}}"