- name: Variable for task 
  hosts: remote 
  vars:
    COURSE: "Devops with asw"
    TRINER: " SIVE "
    DURATION: " 4 months"
  tasks:
  - name: varisble from task 1
    vars:
      COURSE: "DEVOPS"
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}}, Triner is : {{TRINER}}, Duration takes {{DURATION}}"

   - name: varisble from task 2
     ansible.builtin.debug:
        msg: "I am learning {{COURSE}}, Triner is : {{TRINER}}, Duration takes {{DURATION}}"