- name: variable from file
  hosts: remote
  vars_files:
  - vars.yaml
  tasks:
  - name: variable take from file
    ansible.builtin.debug:
      mag: "i am learing {{Course}}, Triner is: {{Triner}}, Duration its take {{Duration}}"