- name: varible from file
  hosts: remote
  vars_files:
  - vars.yaml
  tasks:
  - name: varible take from file
    ansible.builtin.debug:
      msg: "HI i am learing {{Course}}, Trainer is: {{Triner}}, Duration its take: {{Duration}}""