- name: prompt lever variable
  hosts: remote
  vars_prompt:
  - name: USERNAME
    prompt: please enter the username
    private: false
  - name: PASSWORD
    prompt: please enter the password 
    private: true
  
  tasks:
  - name: prompt the values in task lever 
    ansible.builtin.debug:
      msg: "USERNAME is: {{USERNAME}} PASSWORD is: {{PASSWORD}}"