- name: prompt 
  hosts: remote
  vars_prompt:
  - name: USERNAME
    prompt: Please enter the username
    private: false
  - name: PASSWORD
    prompt: Please enter the password
    private: true

  tasks:
  - name: prompt variable
    ansible.builtin.debug:
      msg: "USERNAME is : {{USERNAME}}, PASSWORD is: {{PASSWORD}}"