- name: varible from prompt
  hosts: remote
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    password: Please enter the password
    private: true
  tasks:
  - name: prompt variables decleration 
    ansible.builtin.debug:
      msg: "USERNAME is: {{USERNAME}}, PASSWORD is: {{PASSWORD}}"
  