- name: condition
  hosts: web 
  become: yes
  tasks:
  - name: check user 
    ansible.builtin.command: id Nagarjuna
    register: USER
    ignore_errors: true
  
  - name: print user information 
    ansible.builtin.debug:
      msg: "USER Info: {{USER}}"
    
  - name: say hellow
    ansible.builtin.debug:
      msg: "Hellow"
