- name: condition
  hosts: web 
  become: yes
  tasks:
  - name: check user 
    ansible.builtin.command: id Nagarjuna
    register: USER
    ignore_errors: true
  
  - name: print user information 
    ansible.builtin.debug:
      msg: "USER Info: {{USER}}"

  - name: create user
    ansible.builtin.command: useradd Nagarjuna
    when: USER.rc != 0
  
  tasks:
   - name: find user 
    ansible.builtin.command: id Nagarjuna
    register: USERS
    ignore_errors: true
  
  - name: print user information 
    ansible.builtin.debug:
      msg: "USER Info: {{USERS}}"

  - name: user remove
    ansible.builtin.command: userdel Nagarjuna
    when: USERS.rc = 0
    
  - name: say hellow
    ansible.builtin.debug:
      msg: "Hellow"
