- name: print default value
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "Hi : {{ Course | default('Ansible')}}"
  
- name: print in upper case
  hosts: localhost
  vars:
    my_list:  how are you
  tasks:
  - name: uppercase 
    ansible.builtin.debug:
      msg: "Hi {{ my_list | upper }}"
  
- name: print in lower case 
  hosts: localhost
  vars: 
    my_list1: HOW ARE YOU 
  tasks:
  - name: lowercase 
    ansible.builtin.debug:
      msg: "Hi {{ my_list1 | lower }}"

- name: remove duplicates
  hosts: localhosts
  vars:
    numbers: [1, 2, 3, 5, 6, 8, 9, 9, 9, 0, 9]
  tasks:
  - name: remove duplicate
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"


