
- name: print default value
  hosts: localhost
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }}"

    
- name: Upper case
  hosts: localhost
  vars:
    getting: "Hellow, Good morning"
  tasks:
  - name: print in uppercase 
    ansible.builtin.debug:
      msg: "{{ getting | upper }}"    

- name: print lower case 
  hosts: localhost
  vars:
    lower: "HELLO HOW ARE YOU"
  tasks:
  - name: print in lower case
    ansible.builtin.debug:
      msg: "{{ lower | lower }}"

- name: delete duplicates
  hosts: localhost
  vars:
    values: [3 4 5 7 9 1 4 5 0 6]
  tasks: 
  - name: delete duplicate form list 
    ansible.builtin.debug:
      msg: "{{ values | unique }}"


  