
- name: print default value
  hosts: localhost
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible') }}"

    
- name: Upper case
  hosts: localhost
  vars:
    getting: "Hellow, Good morning"
  tasks:
  - name: print in uppercase 
    ansible.builtin.debug:
      msg: "{{ getting | upper }}"    

- name: print lower case 
  hosts: localhost
  vars:
    lower: "HELLO HOW ARE YOU"
  tasks:
  - name: print in lower case
    ansible.builtin.debug:
      msg: "{{ lower | lower }}"

- name: delete duplicates
  hosts: localhost
  vars:
    values: [3, 4, 5, 7, 9, 1, 4, 5, 0, 6]
  tasks: 
  - name: delete duplicate form list 
    ansible.builtin.debug:
      msg: "{{ values | unique }}"

- name: min and max print 
  hosts: localhost
  vars: 
    age: [ 22, 33, 44, 99 ]
  tasks:
  - name: print minimum age amd maximum age 
    ansible.builtin.debug:
      msg: "minimum age is: {{age | min}}, Maximum age is: {{ age | max}}"

- name: convert dictonary to item/list 
  hosts: localhost
  vars: 
    my_dict:
      course: Ansible
      trinter: Siva
      duration: 3 months
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
      msg: " after convert: {{ my_dict | dict2items }}"

- name: convert list to dictonary 
  hosts: localhost
  vars: 
    my_list: 
    - {'key': 'course', 'value': 'Ansible'}
    - {'key': 'trinter', 'value': 'Siva'}
    - {'key': 'duration', 'value': '3 months'}
  tasks:
  - name: before convert list 
    ansible.builtin.debug:
      msg: " before convert {{ my_list }}"
  - name: after convert list 
    ansible.builtin.debug:
      msg: " after convert: {{ my_list | items2dict }}"


  