- name: deinstall nginx 
  hosts: web
  become: yes 
  tasks:
  - name: stop the nginx 
    ansible.builtin.service:
      name: nginx
      state: stopped
  - name: deinstall the nginx 
    ansible.builtin.dnf: 
      name: nginx 
      state: absent

    