- name: install nginx 
  hosts: web 
  become: yes 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest 
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started 
      enable: yes 