- name: varible task
  hosts: web 
  vars: 
    Course: "Teraform"
    Triner: "Siva"
    Duration: "120hr"
  tasks: 
  - name: pring override variables
    vars:
      Course: "Devops"
    ansible.builtin.debug:
      msg: "Hi i am learing {{Course}} Triner {{Triner}}, Duration {{Duration}}"
      
  - name: print variables
    ansible.builtin.debug:
      msg: "Hi i am learing {{Course}} Triner {{Triner}}, Duration {{Duration}}"