- name: varible from file 
  hosts: remote 
  vars_files:
  - vars.yaml
  - name: varible from file
    anisible.built.debug:
      msg: "Hi i am learing {{Course}}, Triner {{Triner}}, Duration {{Duration}} "