- name: varible from file 
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: varible from files 
    ansible.builtin.debug:
      msg: "Hi i am learing {{Course}}, Triner {{Triner}}, Duration {{Duration}} "