- name: variable form file
  hosts: remote
  vars_files:
  - vars.yaml
  tasks:
  - name: variable take from file
    ansible.builtin.debug:
      msg: "I am learing {Course}}, Trainer is {{Triner}}, Duration take{{Duration}}"