- name: vars form prompt 
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter the username
    private: false
  - name: PASSWORD
    prompt: please enter password
    private: true
  tasks:
  - name: prompt for inpits
    ansible.builtin.debug:
      msg: HI i am using {{USERNAME}} and {{PASSWORD}}