- name: varible from prompt 
  hosts: localhosts
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    prompt: please enter password
    private: true
  tasks:
  - name: vari from prompt
    ansible.builtin.debug:
      msg: "Hi i am enter USERNAME {{USERNAME}} PASSWORD is: {{PASSWORD}}"