- name: variable from inventory 
  hosts: localhost
  tasks:
  - name: print  information
    vars:
      TIMINGS: "07:05am IST"
    ansible.builtin.debu:
      msg: " Hi i am learing Course: {{COURSE}}, Triner is: {{TRINER}}, Duration is: {{DURATION}}, timmings {{TIMINGS}}"