- name: variable from inventory 
  hosts: localhost
  tasks:
  - name: print override information
    vars:
      TIMINGS: "07:05am IST"
    ansible.builtin.debug:
      msg: " Hi i am learing Course: {{COURESE}} Triner is: {{TRINER}} Duration is: {{DURATION}} timmings {{TIMINGS}}"