- name: variable from inventory 
  hosts: localhost
  tasks:
    - name: print information
      vars:
      ansible.builtin.debug:
        msg: " Hi i am learing Course: {{COURSE}}, Triner is: {{TRINER}}, Duration is: {{DURATION}}, timmings {{TIMINGS}}"

- name: inventory to varibles
  hosts: localhost
  tasks:
  - name: print variable
    vars:
    ansible.builtin.debug:
      msg: "Hi i am learning {{COURSE}}, triner from {{TRINER}}, durations {{DURATION}}, taiming {{TIMINGS}}"